---
title: Growing With W
subhead: Navigating schools, screens, and everything in between<br /><small class="text-muted">(with my 2e son)</small>
email: FIXME@example.com
description: FIXME!!!
baseurl: ''
url: ''
markdown: kramdown
theme: growing-with-w-theme
# remote_theme: funkfinger/growing-with-w-theme

plugins:
  - jekyll-feed
  # - jekyll-remote-theme

jekyll_pages_api_search:
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body: 
