---
title: Growing With W
email: your-email@example.com
description: Description goes here
baseurl: ''
url: ''
markdown: kramdown
theme: growing-with-w-theme
plugins:
- jekyll-feed
jekyll_pages_api_search:
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body: 
